### ISSUE TITLE
Getting a 404 error when I try to look at other branches?

### ISSUE THREAD

**Issue by anikaraghu** [cs210/ABC-1#7]
Hi Team! Any ideas why this might be happening? Thanks :)

**Comment by karinaasanchez** [comment]
@anikaraghu hi ! I am not having this problem, but I renamed the branch just in case: https://github.com/cs210/ABC-1/tree/feature/political-leaning-predictor-setup

Let me know if this works.

**Comment by phoebek** [comment]
@anikaraghu is this resolved? if not, please let us know!
